
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 150)

print("="*70)
print("DATASET 1: Cellular Network Performance")
print("="*70)
df1 = pd.read_csv('data/raw/cellular_network_performance/cellular_performance.csv')
print(f"Shape: {df1.shape}")
print(df1.head(3))
print("\nColumn dtypes:")
print(df1.dtypes)
print("\nMissing values:")
print(df1.isnull().sum())

print("\n" + "="*70)
print("DATASET 2: RF Signal Data")
print("="*70)
df2 = pd.read_csv('data/raw/rf_signal_data/rf_signal_data.csv')
print(f"Shape: {df2.shape}")
print(df2.head(3))
print("\nColumn dtypes:")
print(df2.dtypes)
print("\nMissing values:")
print(df2.isnull().sum())

print("\n" + "="*70)
print("DATASET 3: Mobile Network Coverage India - 404.csv")
print("="*70)
df3a = pd.read_csv('data/raw/mobile_network_coverage_india/404.csv')
print(f"Shape: {df3a.shape}")
print(df3a.head(3))

print("\n" + "="*70)
print("DATASET 3b: Mobile Network Coverage India - 405.csv")
print("="*70)
df3b = pd.read_csv('data/raw/mobile_network_coverage_india/405.csv')
print(f"Shape: {df3b.shape}")
print(df3b.head(3))

print("\n" + "="*70)
print("DATASET 3c: MCC-MNC India.csv (operator mapping)")
print("="*70)
df3c = pd.read_csv('data/raw/mobile_network_coverage_india/MCC-MNC India.csv')
print(f"Shape: {df3c.shape}")
print(df3c.head(5))
print("\nColumns:", list(df3c.columns))